name: Compile

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Check out the PR branch
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Mypyc and Stubs
        run: pip install "mypy[mypyc]==1.17.0" types-PyYAML types-tqdm

      - name: Install Pandas from Wheel
        # For some reason the workflow keeps installing pandas from source which takes 10 minutes
        # and isn't necessary, so here we force the workflow to use the wheel.
        env:
          PIP_ONLY_BINARY: ":pandas:"
        run: pip install pandas
        
      - name: Install Dependencies
        run: pip install .
        
      - name: Run Mypyc
        env:
          MYPYC_STRICT_DUNDER_TYPING: 1
        run: make build

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: compile C files for source control"
          git push
