name: PyTest

on:
  pull_request:
    branch: master
    paths:
      - '**.py'
      - '**/pytest.yaml'
      - 'pyproject.toml'
      - 'poetry.lock'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        pyversion: [ "3.10", "3.11", "3.12" ]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Python (faster than using Python container)
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-${{ runner.os }}-${{ matrix.pyversion }}-0  # increment to reset cache
          
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true' && matrix.pyversion != '3.8'
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Install Setuptools for `pkg_resources`
        run: poetry run pip install -U setuptools
        
      - name: Install DAO Treasury
        run: poetry run python -m pip install .
        
      - name: Setup brownie networks
        run: |
          poetry run brownie networks modify mainnet host=${{ secrets.WEB3_PROVIDER }}
        continue-on-error: true

      - name: Run test suite
        env:
          BROWNIE_NETWORK_ID: mainnet
          ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN  }}
        run: poetry run pytest
